[application]
name = "wiki-dioxus"
default_platform = "web"
asset_dir = "assets"

[web.app]
title = "RadikalWiki"

[web.wasm_opt]
level = "z"

[web.watcher]
index_on_404 = true
watch_path = ["src", "assets"]
