# Standalone build for the published repo. Generated by
# platform/tangled/publish/gen-standalone.nu; edit that template, not this file.
#
# The build, the devshell and its hooks, and the formatter are shared with
# every other repo published from the monorepo, and live in the standalone
# module. Only what is particular to this project is stated here.
{
  description = "A political conference and discussion platform, in Rust and Dioxus";

  inputs = {
    # Pinned to the same revision the monorepo resolves, so every published
    # repo builds against identical nixpkgs and they cannot drift apart.
    # Change it by re-running the generator, never here.
    nixpkgs.url = "github:NixOS/nixpkgs/fcb8fcd6bf2d0adecae5bd491afaaaf8311b758d";

    flakelight = {
      url = "github:accelbread/flakelight";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    standalone = {
      url = "github:overby-me/nix-standalone";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.flakelight.follows = "flakelight";
    };
  };

  outputs = inputs:
    inputs.flakelight ./. {
      inherit inputs;
      imports = [inputs.standalone.flakelightModules.default];

      description = "A political conference and discussion platform, in Rust and Dioxus";

      standalone = {
        name = "wiki";
        root = ./.;
      };
    };
}
