# Standalone build for this project, as the monorepo sees it. Generated by
# platform/tangled/publish/gen-project.nu; edit that template, not this file.
#
# nix-workspace is a path here, so the monorepo can evaluate its own change to
# it without publishing first, and so the root flake can take this as an
# input and check that it still builds. The published repo gets the same file
# with a Tangled URL, mapped over this one by josh.
#
# The relative path only resolves when this flake is reached through the repo
# root: as a root input, or `nix eval '.?dir=<this directory>#...'`.
{
  description = "A political conference and discussion platform, in Rust and Dioxus";

  inputs.workspace.url = "path:../../platform/nix/workspace";

  outputs = inputs:
    inputs.workspace ./. {
      name = "wiki";
      description = "A political conference and discussion platform, in Rust and Dioxus";
    };
}
