-- 0003: who may recover, and who may end it.
--
-- APPLIED to production on 2026-07-30. Hasura metadata only: no schema change,
-- which is why this file has no statements. It is here because the bin's
-- behaviour lives in these two permissions as much as in 0001's columns, and a
-- rebuilt instance with only the SQL applied would be subtly wrong in both
-- directions — invisible bins for everyone but owners, and a delete-for-good
-- anyone could reach.
--
-- ── 1. `deleted_nodes` SELECT (role `user`) ───────────────────────────────
-- Was: owners of the context, and nobody else.
-- Now:
--   {_or: [
--     {context: {members: {_and: [{owner: {_eq: true}},
--                                 {node_id: {_eq: X-Hasura-User-Id}}]}}},
--     {context: {owner_id: {_eq: X-Hasura-User-Id}}},
--     {deleted_by: {_eq: X-Hasura-User-Id}},
--     {owner_id: {_eq: X-Hasura-User-Id}}
--   ]}
-- An owner still sees the context's whole bin. Everyone else sees what they
-- deleted and what was theirs — which is what they need, since undoing a delete
-- costs nothing if it was a mistake and the alternative is asking an owner.
-- Verified: a member of the same context who neither deleted the row nor owned
-- it gets an empty list.
--
-- ── 2. `nodes` DELETE (role `user`) ───────────────────────────────────────
-- Was: {_or: [<context owner>, {delete: {_eq: true}}]}
-- Now: {_or: [<context owner>,
--             {_and: [{delete: {_eq: true}}, {deleted_at: {_is_null: true}}]}]}
-- The `delete` computed field is the app's ordinary authority: it is what lets a
-- member remove their own reaction, their own speaker entry, their own policy.
-- All of those act on live rows and are untouched. What changes is the binned
-- ones: emptying the bin is the only irreversible act in the feature, so it
-- answers to the context rather than to whoever did the deleting. Without this
-- the owner-only button in `BinApp` would be decoration — verified before the
-- change that a plain member's purge removed the row.
--
-- Verified as role `user` against production, impersonating a plain member of a
-- context and an owner of it, over the whole cycle: bin, appear in the member's
-- bin, stay out of an unrelated member's bin, appear in the owner's, restore,
-- bin again, member purge refused (0 rows), member's live delete still works,
-- owner purge takes it (1 row), row gone.
