-- 0004: what a signed-out visitor may read.
--
-- APPLIED to production on 2026-07-30. Hasura metadata only, hence no
-- statements. Two columns, both needed to render a page that is already public
-- and neither of them private.
--
-- ── `auth.users` SELECT (role `public`) ───────────────────────────────────
-- Added `avatar_url` (was: display_name, id). The node query reads the author
-- through the `owner` relationship, so without it EVERY node query failed for a
-- signed-out visitor: "field 'avatarUrl' not found in type: 'users'" aborts the
-- whole query, not just that field. A public wiki could not open a single page.
-- The value is not new to the public: the `authorAvatar` computed field already
-- returns the same picture to anyone, which is what it was written for. The
-- email stays behind the row rule, as before.
--
-- ── `members` SELECT (role `public`) ──────────────────────────────────────
-- Added `hidden`. It is the flag an owner sets to keep an author off the byline,
-- and the app filters on it, so without it an anonymous reader would be shown
-- authors the owners had deliberately hidden — after the same total failure as
-- above. `email` is NOT added and must not be: member emails are private, which
-- is why the node query stopped asking for them (see graphql::MemberFields).
--
-- Verified anonymously against production, with the exact operations the app
-- builds: path resolve, node with children, the folder listing and the drawer
-- listing all succeed with no auth header at all.
