-- 0006: the index the node search was missing.
--
-- APPLIED to production on 2026-07-31.
--
-- The author picker felt slow, and the database was only part of it — but it
-- was a real part, and this is the half that no client change can fix.
--
-- `search_nodes` asks `name ILIKE '%q%' OR content_text ILIKE '%q%'`.
-- `content_text` has had a trigram index since it was added; `name` never did.
-- An OR can only use indexes when BOTH sides have one — otherwise the planner
-- falls back to a sequential scan and evaluates the expensive content match on
-- every row. Measured on production, for '%Sofie%' across 3994 nodes:
--
--   content_text alone   Bitmap Index Scan      2.7 ms
--   name alone           Seq Scan               6.2 ms
--   the two OR'd         Seq Scan             131.4 ms   <- what the app ran
--   after this index     BitmapOr of both       1.8 ms
--
-- Seventy times faster, and it helps every node search in the app, not only the
-- author picker: the search bar, the invite autocomplete, the drawer's finder.
--
-- Not CONCURRENTLY: Hasura's run_sql wraps statements in a transaction, and on
-- 3994 rows the build took 311 ms, so the write lock is not worth the ceremony.
-- On a table of any size, add CONCURRENTLY and run it outside Hasura.

create index if not exists nodes_name_trgm on nodes using gin (name gin_trgm_ops);

-- pg_trgm is already installed (it is what content_text's index uses), so there
-- is no CREATE EXTENSION here. On a fresh database:
--   create extension if not exists pg_trgm;
--
-- To undo:
--   drop index if exists nodes_name_trgm;
